# Generated by Django 5.2.9 on 2026-01-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0771_alter_realmemoji_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="image_video_preview_size",
            field=models.SmallIntegerField(default=0),
        ),
    ]
