# Generated by Django 5.2.8 on 2025-12-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0771_alter_realmemoji_author"),
    ]
    operations = [
        migrations.AddField(
            model_name="customprofilefield",
            name="use_for_user_matching",
            field=models.BooleanField(default=False),
        ),
    ]
